### PR TITLE
only run JS tests for single plugin if PLUGIN_NAME is defined

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Using the new `--plugin=...` parameter to make sure plugin builds only run tests for their specific plugin, so failures in other plugins do not affect the plugin build's status.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by michalkleiner — APPROVED** [review]

**Comment by sgiehl** [comment]
Note: We maybe should use the `--plugin` option with care. It will also prevent the core javascript tests from running. But imho it can be useful to know if the core javascript tests are still running if a certain plugin is used.

**Comment by diosmosis** [comment]
Why would core javascript tests need to be run in a plugin build? Or why would we need to know if the core tests are still run in the build for a plugin?

**Comment by sgiehl** [comment]
A plugin might break the core tracking even with having succeeding JavaScript plugin tests. Running core tests might show that.

**Comment by diosmosis** [comment]
How would it break core tracking? Through tracker events? Or something else?

**Comment by sgiehl** [comment]
Maybe. That was more a random thought, than something that would have happened in the past.
Being able to be sure, that tracking tests of core succeed with a plugin, is imho better than not knowing it.

**Comment by diosmosis** [comment]
Failure tests could be added to core in that case, ones that simulate broken plugin behavior and make sure the tracker survives? And if it's really an issue that plugin JS can somehow break core tracker JS, core tests can be grouped together (if possible to do a module within a module in qunit) into a `core`  one which is simply run with another tests:run-js command before the `--plugin=PluginName` one. Though it's hard to see what could actually go wrong given core tracker code should not interact with plugin tracker code directly.

**Pull request merged**
